import type { AppLocale } from "@/lib/site-config";

const EXACT_EN: Record<string, string> = {
  "Musisz być zalogowany.": "You must be logged in.",
  "Sprawdź wypełnione pola.": "Check the fields and try again.",
  "Ten nick jest już zajęty. Wybierz inny.": "This username is already taken. Choose another one.",
  "Ten nick jest już zajęty.": "This username is already taken.",
  "Coś poszło nie tak. Spróbuj ponownie.": "Something went wrong. Please try again.",
  "Uzupełnij wszystkie wymagane pola.": "Complete all required fields.",
  "Nieprawidłowy projekt.": "Invalid project.",
  "Nieprawidłowe dane.": "Invalid data.",
  "Nie możesz pisać w tej rozmowie.": "You cannot send messages in this conversation.",
  "Nieprawidłowa wiadomość.": "Invalid message.",
  "Błędne dane.": "Invalid data.",
  "Projekt nie istnieje.": "Project not found.",
  "Rola nie istnieje.": "Role not found.",
  "Ta rola jest już obsadzona.": "This role has already been filled.",
  "Nie możesz aplikować do własnego projektu.": "You cannot apply to your own project.",
  "Nie możesz aplikować do tego projektu.": "You cannot apply to this project.",
  "Masz już oczekujące zgłoszenie do tej roli.": "You already have a pending application for this role.",
  "Brak uprawnień.": "You do not have permission to do this.",
  "Ta osoba nie jest dostępna.": "This person is not available.",
  "Nie możesz zaprosić samego siebie.": "You cannot invite yourself.",
  "Nie można zaprosić tej osoby.": "This person cannot be invited.",
  "Ta osoba już należy do projektu.": "This person is already a project member.",
  "Zaproszenie nie istnieje.": "Invitation not found.",
  "Zgłoszenie nie istnieje.": "Application not found.",
  "To zgłoszenie zostało już rozpatrzone.": "This application has already been reviewed.",
  "To zaproszenie zostało już rozpatrzone.": "This invitation has already been reviewed.",
  "Nie można zaakceptować tego zaproszenia.": "This invitation cannot be accepted.",
  "Rola nie jest już dostępna.": "This role is no longer available.",
  "Za dużo prób rejestracji. Spróbuj ponownie później.": "Too many sign-up attempts. Please try again later.",
  "Konto z tym adresem e-mail już istnieje.": "An account with this email address already exists.",
  "Nie udało się utworzyć konta.": "We could not create your account. Please try again.",
  "Za dużo prób logowania. Spróbuj ponownie za kilkanaście minut.": "Too many login attempts. Please try again in a few minutes.",
  "Nieprawidłowy e-mail lub hasło.": "Incorrect email or password.",
  "To konto zostało zawieszone przez administrację.": "This account has been suspended.",
  "Zaloguj się ponownie.": "Please log in again.",
  "E-mail jest już potwierdzony.": "Your email is already verified.",
  "Za dużo wiadomości. Spróbuj ponownie później.": "Too many messages were requested. Please try again later.",
  "Wysłaliśmy nowy link weryfikacyjny.": "We sent a new verification link.",
  "Nie udało się wysłać wiadomości.": "We could not send the email. Please try again.",
  "Nieprawidłowy link weryfikacyjny.": "Invalid verification link.",
  "Link jest nieprawidłowy albo wygasł.": "This link is invalid or has expired.",
  "Podaj poprawny e-mail.": "Enter a valid email address.",
  "Jeżeli konto istnieje, wysłaliśmy link do resetu hasła.": "If the account exists, we sent a password reset link.",
  "Za dużo prób. Spróbuj ponownie później.": "Too many attempts. Please try again later.",
};


const EXACT_PL: Record<string, string> = {
  "You must be logged in.": "Musisz być zalogowany.",
  "Check the fields and try again.": "Sprawdź wypełnione pola i spróbuj ponownie.",
  "Something went wrong. Please try again.": "Coś poszło nie tak. Spróbuj ponownie.",
  "Invalid data.": "Nieprawidłowe dane.",
  "Enter a valid email address.": "Podaj poprawny adres e-mail.",
  "Password must be at least 12 characters long.": "Hasło musi mieć co najmniej 12 znaków.",
  "Password is too long.": "Hasło jest zbyt długie.",
  "Accept the Terms of Service and Privacy Policy.": "Zaakceptuj Regulamin i Politykę prywatności.",
  "Enter your password.": "Podaj hasło.",
  "Passwords do not match.": "Hasła nie są takie same.",
  "Enter your current password.": "Podaj aktualne hasło.",
  "New password must be at least 12 characters long.": "Nowe hasło musi mieć co najmniej 12 znaków.",
  "New passwords do not match.": "Nowe hasła nie są takie same.",
  "Username must be at least 2 characters long.": "Nick musi mieć co najmniej 2 znaki.",
  "Username can be at most 24 characters long.": "Nick może mieć maksymalnie 24 znaki.",
  "Use letters, numbers and underscores only.": "Użyj tylko liter, cyfr i podkreśleń.",
  "Choose at least one skill.": "Wybierz przynajmniej jedną umiejętność.",
  "Choose at least one option.": "Zaznacz przynajmniej jedną opcję.",
  "Choose at least one collaboration language.": "Wybierz przynajmniej jeden język współpracy.",
  "Enter a valid http:// or https:// URL.": "Podaj poprawny adres URL zaczynający się od http:// lub https://.",
  "Enter a github.com URL.": "Podaj adres z domeny github.com.",
  "Enter a linkedin.com URL.": "Podaj adres z domeny linkedin.com.",
  "Enter a project name.": "Podaj nazwę projektu.",
  "Add a short tagline.": "Dodaj krótki opis projektu.",
  "Describe the project in at least 20 characters.": "Opisz projekt w co najmniej 20 znakach.",
  "Choose at least one category.": "Wybierz przynajmniej jedną kategorię.",
  "Add at least one technology.": "Dodaj przynajmniej jedną technologię.",
  "Add at least one open role.": "Dodaj przynajmniej jedną otwartą rolę.",
  "Add the project's next goal.": "Podaj najbliższy cel projektu.",
  "Choose at least one project characteristic.": "Wybierz przynajmniej jedną cechę projektu.",
  "Project updates cannot be empty.": "Aktualizacja projektu nie może być pusta.",
  "Message cannot be empty.": "Wiadomość nie może być pusta.",
  "Message can be at most 800 characters long.": "Wiadomość może mieć maksymalnie 800 znaków.",
  "Choose at least one strength.": "Wybierz przynajmniej jedną mocną stronę współpracy.",
  "Choose up to 3 strengths.": "Wybierz maksymalnie 3 mocne strony.",
  "Invalid project.": "Nieprawidłowy projekt.",
  "Project not found.": "Projekt nie istnieje.",
  "Role not found.": "Rola nie istnieje.",
  "This role has already been filled.": "Ta rola jest już obsadzona.",
  "You cannot apply to your own project.": "Nie możesz aplikować do własnego projektu.",
  "You cannot apply to this project.": "Nie możesz aplikować do tego projektu.",
  "You already have a pending application for this role.": "Masz już oczekujące zgłoszenie do tej roli.",
  "You do not have permission to do this.": "Brak uprawnień.",
  "Too many attempts. Please try again later.": "Za dużo prób. Spróbuj ponownie później.",
  "The verification session expired. Please log in again.": "Sesja weryfikacji wygasła. Zaloguj się ponownie.",
  "Too many attempts. Please log in again.": "Za dużo prób. Zaloguj się ponownie.",
  "The code expired. Please log in again.": "Kod wygasł. Zaloguj się ponownie.",
  "Invalid code.": "Nieprawidłowy kod.",
  "Please log in again.": "Zaloguj się ponownie.",
  "Your email is already verified.": "Adres e-mail jest już potwierdzony.",
  "Too many email requests. Please try again later.": "Za dużo próśb o wiadomość. Spróbuj ponownie później.",
  "We sent a new verification link.": "Wysłaliśmy nowy link weryfikacyjny.",
  "We could not send the email.": "Nie udało się wysłać wiadomości e-mail.",
  "Invalid verification link.": "Nieprawidłowy link weryfikacyjny.",
  "This link is invalid or has expired.": "Link jest nieprawidłowy albo wygasł.",
  "If the account exists, we sent a password reset link.": "Jeżeli konto istnieje, wysłaliśmy link do resetu hasła.",
  "The password reset link is invalid or has expired.": "Link do resetu hasła jest nieprawidłowy albo wygasł.",
  "Invalid collaboration.": "Nieprawidłowa współpraca.",
  "Collaboration not found.": "Nie znaleziono współpracy.",
  "You cannot update this collaboration.": "Nie możesz zaktualizować tej współpracy.",
  "Collaboration confirmation opens 7 days after the person joins the project.": "Potwierdzenie współpracy jest dostępne 7 dni po dołączeniu osoby do projektu.",
};

const PREFIX_PL: Array<[string, string]> = [
  ["Note can be at most", "Notatka może mieć maksymalnie"],
  ["Headline can be at most", "Nagłówek może mieć maksymalnie"],
  ["Use up to", "Użyj maksymalnie"],
];

const PREFIX_EN: Array<[string, string]> = [
  ["Nick musi mieć min.", "Username must have at least"],
  ["Nick może mieć maks.", "Username can have at most"],
  ["Wybierz przynajmniej jedną umiejętność.", "Choose at least one skill."],
  ["Wybierz przynajmniej jeden język.", "Choose at least one collaboration language."],
  ["Zaznacz przynajmniej jedną opcję.", "Choose at least one option."],
  ["Podaj nazwę projektu.", "Enter a project name."],
  ["Dodaj krótki opis (tagline).", "Add a short project tagline."],
  ["Opisz projekt szerzej", "Add a longer project description"],
  ["Wybierz przynajmniej jedną kategorię.", "Choose at least one category."],
  ["Dodaj przynajmniej jedną technologię.", "Add at least one technology."],
  ["Dodaj przynajmniej jedną otwartą rolę.", "Add at least one open role."],
  ["Podaj najbliższy cel projektu.", "Add the project's next goal."],
  ["Wybierz charakter projektu.", "Choose the project character."],
];

export function appMessage(message: string | undefined | null, locale: AppLocale, fallbackEn = "Something went wrong. Please try again.") {
  if (!message) return locale === "en" ? fallbackEn : "Coś poszło nie tak. Spróbuj ponownie.";

  if (locale === "en") {
    if (EXACT_EN[message]) return EXACT_EN[message];
    for (const [pl, en] of PREFIX_EN) if (message.startsWith(pl)) return en;
    return message;
  }

  if (EXACT_PL[message]) return EXACT_PL[message];
  for (const [en, pl] of PREFIX_PL) if (message.startsWith(en)) return message.replace(en, pl);
  return message;
}
