import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ExternalLink, UsersRound } from "lucide-react";
import { Avatar } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { HackathonIdentityMark } from "@/components/hackathons/hackathon-identity-mark";
import { HackathonJoinForm } from "@/components/hackathons/hackathon-join-form";
import { CreateHackathonTeamForm } from "@/components/hackathons/create-hackathon-team-form";
import { HackathonInviteDecision, HackathonRequestDecision, InviteHackathonParticipantButton, LeaveHackathonTeamButton, PauseHackathonMatchingButton, RequestToJoinTeamButton, SuggestedTeamButton } from "@/components/hackathons/hackathon-actions";
import { getCurrentUser } from "@/lib/auth";
import { HACKATHON_AVAILABILITY_LABELS, HACKATHON_GOAL_LABELS, ROLE_LABELS } from "@/lib/constants";
import { getHackathonPhase, HACKATHON_PHASE_LABELS, hackathonDateLabel, hackathonLocationLabel } from "@/lib/hackathons";
import { getHackathonBySlug, getHackathonParticipation, getHackathonRoleCounts, getHackathonStats, getHackathonTeamForUser, listHackathonMatches, listHackathonTeams, listIncomingHackathonInvites, listPendingHackathonTeamRequests, teamMissingRoles } from "@/server/data/hackathons";

export const metadata: Metadata = { title: "Znajdź team na hackathon — BuildCrew" };

export default async function HackathonDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const user = await getCurrentUser(); if (!user) redirect("/login");
  const { slug } = await params;
  const event = await getHackathonBySlug(slug); if (!event) notFound();
  const phase = getHackathonPhase(event);
  const [stats, roleCounts, participation, team, invites] = await Promise.all([
    getHackathonStats(event.id),
    getHackathonRoleCounts(event.id),
    getHackathonParticipation(event.id, user.id),
    getHackathonTeamForUser(event.id, user.id),
    listIncomingHackathonInvites(event.id, user.id),
  ]);
  const [matches, teams, requests] = await Promise.all([
    participation?.status === "LOOKING" && !team ? listHackathonMatches(event.id, user.id) : Promise.resolve([]),
    listHackathonTeams(event.id, user.id),
    team?.viewerIsLead ? listPendingHackathonTeamRequests(team.id, user.id) : Promise.resolve([]),
  ]);

  return (
    <div>
      <div className="mb-5"><Link href="/hackathons" className="text-[13px] font-medium text-[var(--bc-muted)] hover:text-[var(--bc-ink)] hover:underline">← Wszystkie hackathony</Link></div>
      <header className="grid gap-5 border-b border-[var(--bc-line-strong)] pb-6 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-start">
        <div className="flex min-w-0 gap-4"><HackathonIdentityMark name={event.name} coverImageUrl={event.coverImageUrl} className="h-16 w-16" /><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="text-[28px] font-semibold tracking-[-0.03em]">{event.name}</h1><Badge variant={phase === "TEAM_FORMING" ? "default" : "secondary"}>{HACKATHON_PHASE_LABELS[phase]}</Badge>{event.isPartner ? <Badge variant="outline">Partner BuildCrew</Badge> : null}</div><p className="mt-2 max-w-[760px] text-[15px] leading-6 text-[var(--bc-muted)]">{event.summary}</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-[13px] text-[var(--bc-faint)]"><span>{hackathonDateLabel(event.startsAt, event.endsAt)}</span><span>{hackathonLocationLabel(event.locationType, event.city)}</span>{event.organizerName ? <span>Organizator: {event.organizerName}</span> : null}</div></div></div>
        <div className="flex flex-wrap gap-2 lg:justify-end"><Button asChild variant="outline"><a href={event.officialUrl} target="_blank" rel="noopener noreferrer">Oficjalna strona <ExternalLink className="ml-1.5 h-3.5 w-3.5" /></a></Button>{event.registrationUrl ? <Button asChild><a href={event.registrationUrl} target="_blank" rel="noopener noreferrer">Oficjalne zapisy <ExternalLink className="ml-1.5 h-3.5 w-3.5" /></a></Button> : null}</div>
      </header>

      <div className="grid gap-8 pt-6 xl:grid-cols-[minmax(0,1fr)_300px]">
        <main className="min-w-0 space-y-8">
          {invites.length && !team ? <section className="border-l-2 border-[var(--bc-accent)] pl-4"><p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-[var(--bc-faint)]">Zaproszenia</p><div className="mt-3 space-y-3">{invites.map((invite) => <div key={invite.id} className="flex flex-col gap-3 border-b border-[var(--bc-line)] pb-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">{invite.teamName}</p><p className="mt-1 text-[13px] text-[var(--bc-muted)]">{invite.inviterUsername} zaprasza Cię do teamu.{invite.message ? ` ${invite.message}` : ""}</p></div><HackathonInviteDecision inviteId={invite.id} /></div>)}</div></section> : null}

          {phase === "TEAM_FORMING" && !team ? <HackathonJoinForm hackathonId={event.id} eventThemes={event.themes} minTeamSize={event.minTeamSize} maxTeamSize={event.maxTeamSize} initial={participation ? { role: participation.role, technologies: participation.technologies, themes: participation.themes, hasIdea: participation.hasIdea, ideaSummary: participation.ideaSummary, goal: participation.goal, availability: participation.availability, preferredTeamSize: participation.preferredTeamSize } : null} /> : null}

          {phase === "TEAM_FORMING" && participation?.status === "LOOKING" && !team ? <section><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-[var(--bc-faint)]">Team matching</p><h2 className="mt-1 text-[20px] font-semibold">Nie masz ekipy? Są dwa sposoby.</h2><p className="mt-1 max-w-[700px] text-sm leading-5 text-[var(--bc-muted)]">BuildCrew może utworzyć dla Ciebie team i wysłać zaproszenia do najlepiej pasujących osób albo możesz przejrzeć ludzi i zespoły samodzielnie.</p></div><div className="flex flex-wrap gap-2"><SuggestedTeamButton hackathonId={event.id} /><CreateHackathonTeamForm hackathonId={event.id} minTeamSize={event.minTeamSize} maxTeamSize={event.maxTeamSize} /></div></div>
            <div className="mt-6"><div className="flex items-center justify-between gap-3"><h3 className="text-[16px] font-semibold">Osoby, z którymi warto porozmawiać</h3><span className="text-[12px] text-[var(--bc-faint)]">Reguły: rola · kierunek · czas · stack</span></div><div className="mt-2 border-t border-[var(--bc-line-strong)]">{matches.map((match) => <article key={match.userId} className="grid gap-3 border-b border-[var(--bc-line)] py-4 md:grid-cols-[220px_minmax(0,1fr)_90px] md:items-center"><Link href={`/builders/${match.userId}`} className="flex items-center gap-3"><Avatar username={match.username} seed={match.avatarEmoji || match.userId} size="sm" className="h-9 w-9 text-[12px]" /><div><p className="text-sm font-semibold">{match.username}</p><p className="text-[12px] text-[var(--bc-muted)]">{ROLE_LABELS[match.role]}</p></div></Link><div><p className="text-[11px] font-medium uppercase tracking-[0.08em] text-[var(--bc-faint)]">Dlaczego warto porozmawiać</p><p className="mt-1 text-[13px] leading-5 text-[var(--bc-muted)]">{match.reasons.slice(0, 2).join(" ") || "Jesteście w tej samej puli wydarzenia."}</p></div><div className="md:text-right"><span className="text-[14px] font-semibold tabular-nums">{match.score}%</span><Link href={`/builders/${match.userId}`} className="mt-1 block text-[12px] font-medium hover:underline">Profil →</Link></div></article>)}{!matches.length ? <p className="border-b border-[var(--bc-line)] py-5 text-sm text-[var(--bc-muted)]">Na razie nie ma innych aktywnych osób w puli. Twój profil zostaje widoczny dla kolejnych uczestników.</p> : null}</div></div>
          </section> : null}

          {team ? <section><div className="flex items-end justify-between gap-4"><div><p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-[var(--bc-faint)]">Twój team</p><h2 className="mt-1 text-[20px] font-semibold">{team.name}</h2><p className="mt-1 text-sm text-[var(--bc-muted)]">{team.members.length}/{team.targetSize} osób{team.ideaTitle ? ` · ${team.ideaTitle}` : ""}</p></div><LeaveHackathonTeamButton teamId={team.id} /></div><div className="mt-4 border-t border-[var(--bc-line-strong)]">{team.members.map((member) => <div key={member.userId} className="flex items-center justify-between gap-3 border-b border-[var(--bc-line)] py-3"><Link href={`/builders/${member.userId}`} className="flex items-center gap-3"><Avatar username={member.username} seed={member.avatarEmoji || member.userId} size="sm" className="h-9 w-9 text-[12px]" /><div><p className="text-sm font-semibold">{member.username}{member.isLead ? <span className="ml-2 text-[11px] font-medium text-[var(--bc-faint)]">prowadzący</span> : null}</p><p className="text-[12px] text-[var(--bc-muted)]">{member.role ? ROLE_LABELS[member.role] : "Builder"}</p></div></Link></div>)}</div>{team.viewerIsLead && team.members.length < team.targetSize ? <div className="mt-5"><p className="text-[13px] font-semibold">Znajdź brakujące osoby</p><p className="mt-1 text-[12px] text-[var(--bc-muted)]">Masz {team.targetSize - team.members.length} wolne {team.targetSize - team.members.length === 1 ? "miejsce" : "miejsca"}. Zaproś osoby z puli wydarzenia.</p><div className="mt-3 border-t border-[var(--bc-line)]">{(await listHackathonMatches(event.id, user.id)).slice(0, 6).map((match) => <div key={match.userId} className="flex flex-col gap-3 border-b border-[var(--bc-line)] py-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><Avatar username={match.username} seed={match.avatarEmoji || match.userId} size="sm" className="h-8 w-8 text-[11px]" /><div><p className="text-sm font-medium">{match.username} · {ROLE_LABELS[match.role]}</p><p className="text-[12px] text-[var(--bc-muted)]">{match.reasons[0] ?? "Szuka teamu na ten sam hackathon."}</p></div></div><InviteHackathonParticipantButton teamId={team.id} inviteeId={match.userId} /></div>)}</div></div> : null}
            {requests.length ? <div className="mt-6"><p className="text-[13px] font-semibold">Zgłoszenia do teamu · {requests.length}</p><div className="mt-2 border-t border-[var(--bc-line)]">{requests.map((request) => <div key={request.id} className="flex flex-col gap-3 border-b border-[var(--bc-line)] py-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><Avatar username={request.username} seed={request.avatarEmoji || request.applicantId} size="sm" className="h-8 w-8 text-[11px]" /><div><p className="text-sm font-medium">{request.username}{request.role ? ` · ${ROLE_LABELS[request.role]}` : ""}</p><p className="text-[12px] text-[var(--bc-muted)]">{request.message || "Chce dołączyć do Waszego teamu."}</p></div></div><HackathonRequestDecision requestId={request.id} /></div>)}</div></div> : null}</section> : null}

          {!team ? <section><div><p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-[var(--bc-faint)]">Otwarte teamy</p><h2 className="mt-1 text-[18px] font-semibold">Zespoły szukające ostatnich osób</h2></div><div className="mt-3 border-t border-[var(--bc-line-strong)]">{teams.filter((item) => item.members.length < item.targetSize).map((item) => { const missing = teamMissingRoles(item.members); return <article key={item.id} className="grid gap-3 border-b border-[var(--bc-line)] py-4 sm:grid-cols-[minmax(0,1fr)_220px_auto] sm:items-center"><div><p className="text-sm font-semibold">{item.name}</p><p className="mt-1 text-[13px] text-[var(--bc-muted)]">{item.ideaTitle || item.ideaSummary || "Team szuka uzupełniających ról na wydarzenie."}</p></div><div><p className="text-[11px] font-medium uppercase tracking-[0.08em] text-[var(--bc-faint)]">Skład</p><p className="mt-1 text-[13px]">{item.members.length}/{item.targetSize} · {item.members.map((member) => member.role ? ROLE_LABELS[member.role] : "Builder").join(" · ")}</p>{missing.length ? <p className="mt-1 text-[12px] text-[var(--bc-muted)]">Może brakować: {missing.slice(0, 2).map((role) => ROLE_LABELS[role]).join(" / ")}</p> : null}</div><RequestToJoinTeamButton teamId={item.id} disabled={!participation || participation.status !== "LOOKING" || phase !== "TEAM_FORMING"} alreadyRequested={item.viewerRequestStatus === "PENDING"} /></article>; })}{!teams.some((item) => item.members.length < item.targetSize) ? <p className="border-b border-[var(--bc-line)] py-5 text-sm text-[var(--bc-muted)]">Nie ma jeszcze publicznie formujących się teamów.</p> : null}</div></section> : null}

          {event.description ? <section className="border-t border-[var(--bc-line-strong)] pt-6"><h2 className="text-[18px] font-semibold">O wydarzeniu</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[var(--bc-muted)]">{event.description}</p></section> : null}
        </main>

        <aside className="space-y-5 xl:sticky xl:top-6 xl:self-start">
          <div className="border-t border-[var(--bc-line-strong)] pt-4"><p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-[var(--bc-faint)]">Pula BuildCrew</p><div className="mt-3 grid grid-cols-3 gap-3"><div><p className="text-[18px] font-semibold tabular-nums">{stats.participantCount}</p><p className="text-[11px] text-[var(--bc-faint)]">uczestników</p></div><div><p className="text-[18px] font-semibold tabular-nums">{stats.lookingCount}</p><p className="text-[11px] text-[var(--bc-faint)]">szuka teamu</p></div><div><p className="text-[18px] font-semibold tabular-nums">{stats.teamCount}</p><p className="text-[11px] text-[var(--bc-faint)]">teamów</p></div></div></div>
          {roleCounts.length ? <div className="border-t border-[var(--bc-line)] pt-4"><p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-[var(--bc-faint)]">Role w puli</p><div className="mt-2 space-y-2">{roleCounts.map((row) => <div key={row.role} className="flex items-center justify-between text-[13px]"><span className="text-[var(--bc-muted)]">{ROLE_LABELS[row.role]}</span><span className="font-medium tabular-nums">{row.count}</span></div>)}</div></div> : null}
          {participation ? <div className="border-t border-[var(--bc-line)] pt-4"><p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-[var(--bc-faint)]">Twoje ustawienia</p><dl className="mt-2 space-y-2 text-[13px]"><div className="flex justify-between gap-3"><dt className="text-[var(--bc-muted)]">Rola</dt><dd className="font-medium">{ROLE_LABELS[participation.role]}</dd></div><div className="flex justify-between gap-3"><dt className="text-[var(--bc-muted)]">Cel</dt><dd className="max-w-[170px] text-right font-medium">{HACKATHON_GOAL_LABELS[participation.goal]}</dd></div><div className="flex justify-between gap-3"><dt className="text-[var(--bc-muted)]">Dostępność</dt><dd className="max-w-[170px] text-right font-medium">{HACKATHON_AVAILABILITY_LABELS[participation.availability]}</dd></div><div className="flex justify-between gap-3"><dt className="text-[var(--bc-muted)]">Status</dt><dd className="font-medium">{participation.status === "LOOKING" ? "Szukam teamu" : participation.status === "PAUSED" ? "Wstrzymane" : "W teamie"}</dd></div></dl>{participation.status === "LOOKING" && !team ? <div className="mt-3"><PauseHackathonMatchingButton hackathonId={event.id} /></div> : null}{participation.status === "PAUSED" ? <p className="mt-3 text-[12px] leading-5 text-[var(--bc-muted)]">Zapisz formularz preferencji ponownie, aby wrócić do puli.</p> : null}</div> : null}
          <div className="border-t border-[var(--bc-line)] pt-4 text-[12px] leading-5 text-[var(--bc-muted)]"><p className="font-medium text-[var(--bc-ink)]">Ważne</p><p className="mt-1">BuildCrew pomaga znaleźć team. Oficjalny udział, regulamin wydarzenia, opłaty i zgody są obsługiwane przez organizatora. {event.isPartner ? "To wydarzenie jest oznaczone jako partner BuildCrew." : "BuildCrew nie jest oznaczone jako organizator ani oficjalny partner tego wydarzenia."}</p></div>
        </aside>
      </div>
    </div>
  );
}
